c
c     PRAIA_occ_tables_to_CDS
c
c
c     Formats prediction tables generated by the PRAIA package. The output is
c     in the CDS format for eletronic publication via CDS web service.
c
c
c     Usage:
c
c
c     PRAIA_occ_tables_to_CDS < PRAIA_occ_tables_to_CDS.dat > tables_to_CDS.log
c
c
c
C     Last update: M. Assafin - 22/Mar/2012
c
c


      IMPLICIT REAL *8 (A-H,O-Z)

      parameter(stdin=5,stdout=6)


      character*50 impcat,outcat

      character*2 ifcat,ifpm


      character*20 ichfil,iobalv
      character*50 mfits
      character*50 catal,ephem,star,output,dplot,mcata

      character*1 isig,isigb


c
c     Reads from input file
c

      write (*,*)

 1    continue


      read (5,*,err=1,end=100) impcat,outcat
      write(6,*) impcat,outcat

      write (*,*)


c
c     Reads input table generated by the PRAIA package
c
c

      open (1,file=impcat)
      open (7,file=outcat)


c


 10   read (1,15,err=10,end=25) iutdi0,iutme0,iutan0,iuth0,iutm0,sut0,
     ?iah,iam,sa,isig,idg,idm,ds,iahb,iamb,sab,isigb,idgb,idmb,dsb,
     ?dista,pang,vsky,pdis,cadmg,camgj,camgh,camgk,alo,iuths,iutms,
     ?dofra,dofde,ifpm,ifcat,kflag,iaerro,iderro,ipma,ipmd

 15   format(1x,2(i2,1x),i4,1x,2(1x,i2),1x,f3.0,2(3x,2(i2,1x),
     ?f7.4,1x,a1,2(i2,1x),1x,f6.3),3x,f5.3,2x,f6.2,f7.2,f6.2,4(1x,
     ?f4.1),f7.0,1x,i2,1x,i2,1x,2(2x,f7.1),2(1x,a2),1x,i1,4(1x,i4))



c


      write (7,20) iutan0,iutme0,iutdi0,iuth0,iutm0,sut0,iah,iam,sa,
     ?isig,idg,idm,ds,iahb,iamb,sab,isigb,idgb,idmb,dsb,dista,pang,vsky,
     ?pdis,cadmg,camgj,camgh,camgk,alo,iuths,iutms,dofra,dofde,ifpm,
     ?ifcat,kflag,iaerro,iderro,ipma,ipmd

 20   format(1x,i4,1x,2(i2.2,1x),2(1x,i2.2),1x,f3.0,2(3x,2(i2.2,1x),
     ?f7.4,1x,a1,2(i2.2,1x),1x,f6.3),3x,f5.3,2x,f6.2,1x,f7.2,1x,f6.2,
     ?4(1x,f4.1),f7.0,1x,i2.2,1x,i2.2,1x,2(2x,f7.1),2(1x,a2),1x,i1,
     ?4(1x,i4))
     

      go to 10




 25   close (1)
      close (7)


c

      go to 1


c

 100  continue



      end




